### ISSUE TITLE
Enhance offload test suite to verify test results

### ISSUE THREAD

**Issue by spall** [llvm-beanz/offload-test-suite#76]
Add support to the offload test suite to support checking test results in the test suite rather than with FileCheck.

Add support to specify Result(s) in the YAML like below:
```
Results:
- Result: 
   Rule: ExactCompare
   Actual: Out
   Expected: ExpectedOut
- Result:
   Rule: FuzzyCompare
   Epsilon: 2
   # Other extra fields required by rules would go here as well
   Actual: Out2
   Expected: ExpectedOut2
```

Implement rules, such as 'ExactCompare', necessary to verify the test results of HLSL intrinsics, which produce scalars and vectors of integer and floating point types.
