### ISSUE TITLE
Add test for clamp

### ISSUE THREAD

**Issue by spall** [llvm-beanz/offload-test-suite#84]
In Test\Feature\Intrinsics create, if applicable: (reference the HLSL headers for the types supported by the intrinsic)
- [ ] Test for 16 bit int types (clamp.int16.test)
- [ ] Test for Half type (clamp.fp16.test)
- [ ] Test for 32 bit types (clamp.32.test)
- [ ] Test for 64 bit int types (clamp.int64.test)
- [ ] Test for Double type (clamp.fp64.test)

A .test file should contain 
- [ ] a source portion; If multiple tests can use the same source; it can go in its own file and be referenced in the .test file instead.
```
@@ -0,0 +1,54 @@
#--- source.hlsl

StructuredBuffer<float4> In : register(t0);
RWStructuredBuffer<float> Out : register(u1);

[numthreads(1,1,1)]
void main() {
  Out[0] = length(In[0]); // Test float4
  Out[1] = length(In[1].x); // Test float
  Out[2] = length(In[1].yzw); // Test float3
  Out[3] = length(In[1].yz); // Test float2
}
```
- [ ] a  yaml portion
```
//--- pipeline.yaml; If multiple test can use the same YAML; it can go in its own file and be referenced in the .test file instead.

---
Shaders:
  - Stage: Compute
    Entry: main
    DispatchSize: [1, 1, 1]
Buffers:
  - Name: In
    Format: Float32
    Stride: 16
    Data: [ 4, 4, 4, 4, 3.14159, 0, 5, 12 ]
  - Name: Out
    Format: Float32
    Stride: 4
    ZeroInitSize: 12
DescriptorSets:
  - Resources:
    - Name: In
      Kind: StructuredBuffer
      DirectXBinding:
        Register: 0
        Space: 0
    - Name: Out
      Kind: RWStructuredBuffer
      DirectXBinding:
        Register: 1
        Space: 0
...
#--- end
```
- [ ] A run portion
```
# UNSUPPORTED: Clang-Vulkan
# RUN: split-file %s %t
# RUN: %dxc_target -T cs_6_5 -Fo %t.o %t/source.hlsl
# RUN: %offloader %t/pipeline.yaml %t.o 
```
Currently all tests should include `# UNSUPPORTED: Clang-Vulkan`.
Tests for 16 bit floating point should have a `# REQUIRES: Half`.
Tests for 16 bit integer should have a `# REQUIRES: Int16`.
Tests for 64 bit floating point should have a `# REQUIRES: Double`.
Tests for 64 bit integer should have a `# REQUIRES: Int64`.
